services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lorecrafter
    ports:
      - '8000:8000'
    volumes:
      - ./certs:/var/www/.cache
    env_file:
      - .env
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@db:5432/lorecrafter?sslmode=disable
      - VALKEY_ADDRESS=cache:6379
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lorecrafter
    ports:
      - '5432:5432'
    networks:
      - app-network
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  db-test:
    image: postgres:17-alpine
    container_name: db_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lorecrafter_test
    ports:
      - '5433:5432'
    networks:
      - app-network
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  cache:
    image: valkey/valkey:7.2
    container_name: cache
    ports:
      - '6379:6379'
    networks:
      - app-network
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  cache-ui:
    image: docker.io/hibiken/asynqmon
    container_name: cache-ui
    networks:
      - app-network
    ports:
      - '8001:8080'
    environment:
      - REDIS_URL=redis://cache:6379

networks:
  app-network:
    driver: bridge
