// Package docs is generated by Swag. It contains the Swagger documentation.
package docs

// This file will be replaced by the generated Swagger documentation.
// Run `swag init -g cmd/api/docs.go -o cmd/api/docs` to generate the documentation.
