# .github/workflows/deploy.yml
name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          args:
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            PASETO_PRIVATE_KEY=${{ secrets.PASETO_PRIVATE_KEY }}
            PASETO_PUBLIC_KEY=${{ secrets.PASETO_PUBLIC_KEY }}
            POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DBNAME=${{ secrets.POSTGRES_DBNAME }}
            POSTGRES_SSLMODE=${{ secrets.POSTGRES_SSLMODE }}
            POSTGRES_URL=${{ secrets.POSTGRES_URL }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lorecrafter:latest

    # - name: Deploy to production

    # - name: Run database migrations